name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main, deploy ]
    paths:
      - 'frontend/**'
  # –í–æ–∑–º–æ–∂–Ω–æ—Å—Ç—å –∑–∞–ø—É—Å–∫–∞ –≤—Ä—É—á–Ω—É—é –∏–∑ –∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å–∞ GitHub
  workflow_dispatch:

# –ü—Ä–∞–≤–∞, –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã–µ –¥–ª—è –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è –¥–µ–ø–ª–æ—è –Ω–∞ GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CI: false # –ü—Ä–µ–¥–æ—Ç–≤—Ä–∞—â–∞–µ—Ç –æ–±—Ä–∞–±–æ—Ç–∫—É –ø—Ä–µ–¥—É–ø—Ä–µ–∂–¥–µ–Ω–∏–π –∫–∞–∫ –æ—à–∏–±–æ–∫
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v3

      - name: Setup Node.js ‚öôÔ∏è
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/ozon-web/package-lock.json'

      - name: Install Dependencies üì¶
        run: |
          cd frontend/ozon-web
          npm ci

      - name: Build üîß
        env:
          ESLINT_NO_DEV_ERRORS: true
          CI: false
        run: |
          cd frontend/ozon-web
          npm run build

      - name: Deploy to GitHub Pages üöÄ
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/ozon-web/build
          branch: gh-pages
          clean: true 